import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Menu } from "lucide-react";
import { Button } from "@/components/ui/Button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/DropdownMenu";
import DropdownModeToggle from "@/components/DropdownModeToggle";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${inter.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="w-full bg-green-600 h-16 flex items-center justify-between p-3">
            <div className="w-9 h-9 bg-zinc-700 rounded-lg flex items-center justify-center">
              FB
            </div>
            <div>OpenBeatz 2025</div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button className="w-9 h-9">
                  <Menu />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>Logout</DropdownMenuItem>
                <DropdownModeToggle />
              </DropdownMenuContent>
            </DropdownMenu>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
